### ISSUE TITLE
0.5.0 Release?

### ISSUE THREAD

**Issue by misterdorm** [bradleyd/shelltastic#2]
Any reason a release wasn't created for 0.5.0?  We'd like to use the new `start` method, but 0.4.0 is the latest available on rubygems.org.  Thanks!

**Comment by bradleyd** [comment]
No reason just time and quarantine. I have not been in the Ruby world for a little while, can you explain what `start` method you are referring to.

Thanks again

**Comment by misterdorm** [comment]
Thanks for the response.  We ended up working around this a different way, so it's no longer as critical.  But we wanted to be able to use `start` to kick off a background process.  And that method wasn't added until 0.5.0.

**Comment by bradleyd** [comment]
Hmm, it has been awhile since i looked into this. It appears i never cut a release 0.5.0. Glad you got a work around. I will look at this over the weekend and see if I can push something up!

Thanks

**Comment by bradleyd** [comment]
Only a year later and I pushed it up :) Time is a funny thing during a pandemic. Sorry for the loooooong delay.
